name: lqyRL
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch=2.6.0
  - pytorch-cuda=12.1
  - torchaudio=2.6.0
  - torchvision=0.21.0
  - numpy=1.26.4
  - pip:
      - accelerate==1.5.1
      - transformers==4.51.3
      - datasets==3.3.2
      - huggingface-hub==0.30.2
      - safetensors==0.5.3
      - tiktoken==0.9.0
      - tokenizers==0.21.0
      - peft==0.14.0
      - fastapi==0.115.11
      - uvicorn==0.34.0
      - pydantic==2.10.6
      - ray==2.43.0
      - wandb==0.19.8
      - omegaconf==2.3.0
      - hydra-core==1.3.2
      - einops==0.8.1
      - openai==1.66.3
      - anthropic==0.50.0
      - requests
      - tqdm
      - psutil
      - colorama
      - pyyaml
      - numpy
      - scipy
      - pandas
      - matplotlib
      - ipython
      - jupyter
      - gym==0.26.2
      - gymnasium==1.1.1
      - vllm==0.8.2
      - xformers==0.0.29.post2 