name: lqyRL
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch=2.6.0
  - pytorch-cuda=12.1
  - torchaudio=2.6.0
  - torchvision=0.21.0
  - numpy=1.26.4
  - pip:
      - absl-py==2.2.2
      - accelerate==1.5.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.13
      - aiohttp-cors==0.8.1
      - aiosignal==1.3.2
      - airportsdata==20250224
      - annotated-types==0.7.0
      - anthropic==0.50.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.8.0
      - astor==0.8.1
      - asttokens==3.0.0
      - attrs==25.2.0
      - beautifulsoup4==4.13.4
      - blake3==1.0.4
      - blinker==1.9.0
      - blis==1.2.1
      - build==1.2.2.post1
      - cachetools==5.5.2
      - catalogue==2.0.10
      - cleantext==1.1.4
      - click==8.1.8
      - cloudpathlib==0.21.0
      - cloudpickle==3.1.1
      - cmake==4.0.0
      - codetiming==1.4.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - colorful==0.5.6
      - comm==0.2.2
      - compressed-tensors==0.9.2
      - confection==0.1.5
      - contourpy==1.3.1
      - cupy-cuda12x==13.4.1
      - cycler==0.12.1
      - cymem==2.0.11
      - cython==3.0.12
      - datasets==3.3.2
      - debugpy==1.8.14
      - decorator==5.2.1
      - depyf==0.18.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distlib==0.3.9
      - distro==1.9.0
      - dnspython==2.7.0
      - docker-pycreds==0.4.0
      - duckduckgo-search==8.0.1
      - dynaconf==3.2.10
      - einops==0.8.1
      - email-validator==2.2.0
      - eval-type-backport==0.2.2
      - executing==2.2.0
      - faiss-cpu==1.11.0
      - farama-notifications==0.0.4
      - fastapi==0.115.11
      - fastapi-cli==0.0.7
      - fastrlock==0.8.3
      - filelock==3.18.0
      - flask==3.1.0
      - flatbuffers==25.2.10
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - gdown==5.2.0
      - gguf==0.10.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-api-core==2.24.2
      - google-auth==2.40.0
      - googleapis-common-protos==1.70.0
      - griffe==1.7.3
      - grpcio==1.71.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - gym-sokoban==0.0.6
      - gymnasium==1.1.1
      - h11==0.14.0
      - h2==4.2.0
      - hpack==4.1.0
      - html2text==2025.4.15
      - httpcore==1.0.7
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.30.2
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - hyperframe==6.1.0
      - imageio==2.37.0
      - importlib-metadata==8.6.1
      - inquirerpy==0.3.4
      - interegular==0.3.3
      - ipython==8.36.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.6
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jiter==0.9.0
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyterlab-widgets==3.0.14
      - kiwisolver==1.4.8
      - langcodes==3.5.0
      - language-data==1.3.0
      - lark==1.2.2
      - llguidance==0.7.19
      - llvmlite==0.43.0
      - lm-format-enforcer==0.10.11
      - lxml==5.4.0
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistral-common==1.5.4
      - msgpack==1.1.0
      - msgspec==0.19.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - murmurhash==1.0.12
      - nest-asyncio==1.6.0
      - ninja==1.11.1.4
      - nltk==3.9.1
      - numba==0.60.0
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - onnxruntime==1.21.1
      - openai==1.66.3
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-python-headless==4.11.0.86
      - orjson==3.10.15
      - outlines==0.1.11
      - outlines-core==0.1.26
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - partial-json-parser==0.2.1.1.post5
      - peft==0.14.0
      - pexpect==4.9.0
      - pfzy==0.3.4
      - platformdirs==4.3.6
      - preshed==3.0.9
      - primp==0.15.0
      - prometheus-client==0.21.1
      - prometheus-fastapi-instrumentator==7.0.2
      - prompt-toolkit==3.0.50
      - propcache==0.3.0
      - proto-plus==1.26.1
      - protobuf==5.29.3
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - py-spy==0.4.0
      - pyairports==2.1.1
      - pyarrow==19.0.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybind11==2.13.6
      - pycountry==24.6.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygame==2.6.1
      - pygments==2.19.1
      - pyjnius==1.6.1
      - pylatexenc==2.10
      - pyparsing==3.2.1
      - pyproject-hooks==1.2.0
      - pyserini==0.44.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - pytz==2025.1
      - pyzmq==26.3.0
      - rank-bm25==0.2.2
      - rapidfuzz==3.13.0
      - ray==2.43.0
      - referencing==0.36.2
      - regex==2024.11.6
      - rich==14.0.0
      - rich-toolkit==0.14.5
      - rouge-score==0.1.2
      - rpds-py==0.23.1
      - rsa==4.9.1
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - sentencepiece==0.2.0
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.1.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.7
      - spacy==3.8.5
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - stack-data==0.6.3
      - starlette==0.46.1
      - sympy==1.13.1
      - tabulate==0.9.0
      - tavily-python==0.7.0
      - tenacity==9.1.2
      - tensordict==0.6.2
      - thefuzz==0.22.1
      - thinc==8.3.4
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - together==1.5.7
      - tokenizers==0.21.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.51.3
      - triton==3.2.0
      - typer==0.15.3
      - tzdata==2025.1
      - uvicorn==0.34.0
      - uvloop==0.21.0
      - verl==0.2.0.dev0
      - virtualenv==20.31.0
      - vllm==0.8.2
      - wandb==0.19.8
      - wasabi==1.1.3
      - watchfiles==1.0.4
      - wcwidth==0.2.13
      - weasel==0.4.1
      - websockets==15.0.1
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - wrapt==1.17.2
      - xformers==0.0.29.post2
      - xgrammar==0.1.16
      - xxhash==3.5.0
      - yarl==1.18.3
      - zipp==3.21.0 